apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    version: 2.5.25-8562be05--2024-09-19.1726762941
  labels:
    app: infrastructure-documentation
    app.kubernetes.io/name: infrastructure-documentation
    environment: latest
  name: infrastructure-documentation-serviceaccount-latest
---
apiVersion: v1
data:
  nginx.conf: |
    server {
        listen 8080 default_server;
        server_name _;
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }

        # redirect server error pages to the static page /50x.html
        #
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
kind: ConfigMap
metadata:
  annotations:
    version: 2.5.25-8562be05--2024-09-19.1726762941
  labels:
    app: infrastructure-documentation
    app.kubernetes.io/name: infrastructure-documentation
    environment: latest
  name: infrastructure-documentation-nginx-config-latest-b8g9f428f6
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|nginx'
    version: 2.5.25-8562be05--2024-09-19.1726762941
  labels:
    app: infrastructure-documentation
    app.kubernetes.io/name: infrastructure-documentation
    environment: latest
  name: infrastructure-documentation-nginx-service-latest
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: infrastructure-documentation
    app.kubernetes.io/name: infrastructure-documentation
    environment: latest
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: apps|Deployment|default|nginx
    version: 2.5.25-8562be05--2024-09-19.1726762941
  labels:
    app: infrastructure-documentation
    app.kubernetes.io/name: infrastructure-documentation
    environment: latest
  name: infrastructure-documentation-deployment-latest
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: infrastructure-documentation
      app.kubernetes.io/name: infrastructure-documentation
      environment: latest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        version: 2.5.25-8562be05--2024-09-19.1726762941
      labels:
        app: infrastructure-documentation
        app.kubernetes.io/name: infrastructure-documentation
        environment: latest
    spec:
      containers:
      - image: registry.ltc.bcit.ca/web-apps/infrastructure-documentation:2.5.25-8562be05--2024-09-19.1726762941
        name: infrastructure-documentation
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - NET_RAW
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /etc/nginx/conf.d
          name: nginx-config
      serviceAccountName: infrastructure-documentation-serviceaccount-latest
      volumes:
      - configMap:
          name: infrastructure-documentation-nginx-config-latest-b8g9f428f6
        name: nginx-config
      - emptyDir: {}
        name: tmp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    version: 2.5.25-8562be05--2024-09-19.1726762941
  labels:
    app: infrastructure-documentation
    app.kubernetes.io/name: infrastructure-documentation
    environment: latest
  name: infrastructure-documentation-ingress-latest
spec:
  ingressClassName: nginx
  rules:
  - host: latest--infrastructure-documentation.ltc.bcit.ca
    http:
      paths:
      - backend:
          service:
            name: infrastructure-documentation-nginx-service-latest
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - latest--infrastructure-documentation.ltc.bcit.ca
    secretName: infrastructure-documentation-star-ltc-bcit-ca-latest
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  annotations:
    version: 2.5.25-8562be05--2024-09-19.1726762941
  labels:
    environment: latest
  name: infrastructure-documentation-vault-auth-latest
spec:
  kubernetes:
    audiences:
    - vault
    role: infrastructure-documentation-vault-auth-latest
    serviceAccount: infrastructure-documentation-serviceaccount-latest
  method: kubernetes
  mount: kubernetes-latest
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  annotations:
    version: 2.5.25-8562be05--2024-09-19.1726762941
  labels:
    environment: latest
  name: infrastructure-documentation-star-ltc-bcit-ca-latest
spec:
  destination:
    create: true
    name: infrastructure-documentation-star-ltc-bcit-ca-latest
    type: kubernetes.io/tls
  mount: ltc-infrastructure
  path: ssl-certificates/star-ltc-bcit-ca
  refreshAfter: 6h
  type: kv-v2
  vaultAuthRef: infrastructure-documentation-vault-auth-latest
