# Available parameters and their default values for the chart.
#
# Default values reflect the "stable" (production) environment.

# Sets the repo and tag of the deployment.
image:
  repository: "ghcr.io/bcit-ltc/infrastructure-documentation"
  tag: "1.0.7"
  pullPolicy: IfNotPresent
  # pullSecrets:
  #   - name: myregistry-secret

# The organization domain.
defaultDomain: "ltc.bcit.ca"

# Number of pods to run for the deployment.
replicas: 1

# Target port used by the app in the container. Used to configure Deployment and Service resources.
container:
  port: 8080

# Port connecting ingress to the service.
service:
  type: ClusterIP
  port: 80

# Number of seconds the Deployment controller waits before indicating that progress has stalled.
progressDeadlineSeconds: 300

# Number of old Deployment revisions to retain.
revisionHistoryLimit: 2

strategy:
  # The strategy to use for the Deployment.
  type: RollingUpdate
  rollingUpdate:
    # The maximum number of pods that can be created over the desired number of pods.
    maxSurge: 25%
    # The maximum number of pods that can be unavailable during the update.
    maxUnavailable: 25%

resources:
  # For more information on configuring resources, see the K8s documentation:
  # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  cpuRequest: "100m"
  cpuLimit: "100m"
  memRequest: "64Mi"
  memLimit: "128Mi"

serviceAccountName: ""

# podAnnotations:
#   prometheus.io/scrape: "true"

# extraEnv:
#   - name: FOO
#     value: bar

# readinessProbe:
#   httpGet:
#     path: /
#     port: 8080
#   initialDelaySeconds: 5
#   periodSeconds: 10

# livenessProbe:
#   httpGet:
#     path: /
#     port: 8080
#   initialDelaySeconds: 15
#   periodSeconds: 20

ingress:
  annotations: {}
    # |
    # kubernetes.io/tls-acme: "true"
  host: ""          # Optional, defaults to app.name
  tlsSecret: ""     # Defaults to appName.star.ltc.bcit.ca; prefixed with app.name.
  # extraPaths:     # Optional
  #   - path: /api
  #     backend:
  #       service:
  #         name: api-service
  #         port:
  #           number: 3000

#####
##### For later development #####
#####

# # This configures a Statefulset to create a PVC for data
# dataStorage:
#   enabled: false
#   size: 10Gi
#   # Location where the PVC will be mounted.
#   mountPath: "/app/data"

  # # Security context for the pod template and the injector container
  # # The default pod securityContext is:
  # #   runAsNonRoot: true
  # #   runAsGroup: {{ .Values.injector.gid | default 1000 }}
  # #   runAsUser: {{ .Values.injector.uid | default 100 }}
  # #   fsGroup: {{ .Values.injector.gid | default 1000 }}
  # # and for container is
  # #    readOnlyRootFilesystem: true
  # #    allowPrivilegeEscalation: false
  # #    capabilities:
  # #      drop:
  # #        - NET_RAW
  # securityContext:
  #   pod: {}
  #   container: {}

