apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}-config
  namespace: {{ include "app.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  nginx.conf: |
    server {
        listen 8080 default_server;
        server_name _;
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }

        # redirect server error pages to the static page /50x.html
        #
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
