{{- $serviceName := include "app.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $host := printf "%s.%s" (default (include "app.fullname" .) .Values.ingress.host) .Values.defaultDomain -}}
{{- $secretName := printf "%s-%s" (include "app.fullname" .) (.Values.ingress.tlsSecret | default "") | trimSuffix "-" | default (include "app.fullname" .) -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ $host | quote }}
      secretName: {{ $secretName | quote }}
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
        {{- range (.Values.ingress.paths | default (list "/")) }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
        {{- end }}

